### PR TITLE
Zone support

### PR DESCRIPTION
**Pull request by Mina-H-Samy**

### CODE REVIEW

**Comment by nocturnalit** [comment]
Awesome work on this, I was disappointed that I could use Echonet but this works. But just wondering how do I set up zones?

**Comment by zacharyrs** [comment]
Hey @nocturnalit - thanks for reminding me of this!

At the moment, zone support isn't merged into master.
I'm hoping to do a code tidy up and shift to the newer async HASS API, but I've been swamped between uni and work.

I'm not happy merging it into master yet, as it duplicates the MelView instance, however, I also don't see myself touching this for a little while (i.e. until November)...

What I've done for now is merge the changes into https://github.com/zacharyrs/ha-melview/tree/dev, which also has support for dynamic fan speeds.

Give that branch a go and see how it works!

**Comment by zacharyrs** [comment]
Closing this as #14 has been merged into https://github.com/zacharyrs/ha-melview/tree/dev.

**Comment by nocturnalit** [comment]
> Hey @nocturnalit - thanks for reminding me of this!
> 
> At the moment, zone support isn't merged into master.
> I'm hoping to do a code tidy up and shift to the newer async HASS API, but I've been swamped between uni and work.
> 
> I'm not happy merging it into master yet, as it duplicates the MelView instance, however, I also don't see myself touching this for a little while (i.e. until November)...
> 
> What I've done for now is merge the changes into https://github.com/zacharyrs/ha-melview/tree/dev (#14), which also has support for dynamic fan speeds.
> 
> Give that branch a go and see how it works!

Thanks for the update, that’s ok, if I know something is around the corner I won’t worry about swapping the Wi-Fi module.

Fan speed adjustment seems to work, however my unit only has auto, low or high so the medium setting is a bit redundant.

I have the zones setup in google home so I know it’s possible but I’m wanting to control everything from home assist.

I appreciate you time and efforts :)

**Pull request closed without merging**
